jobs:
  include:
  - stage: build
    script: ./gradlew clean build -x test
  - stage: test
    script: ./gradlew test
  - stage: "create docker image"
    script:
    - ./gradlew clean build -x test
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t back .
    - docker run -p 8080:8080 back
    - curl -v localhost:8080/info