sudo: required

language: scala

services:
- docker



jobs:
  include:
  - stage: build
    script: ./gradlew clean build -x test
  - stage: test
    script: ./gradlew test
  - stage: deploy
    install:
      - ./gradlew clean build -x test
      - docker build -t tomtomhackv4/parkathon-back .
      - docker login --username=$DOCKERHUBUSER --password=$DOCKERHUBPASSWORD
    script:
      - docker push tomtomhackv4/parkathon-back