sudo: required

language: scala

services:
- docker



jobs:
  include:
  - stage: build
    script: ./gradlew clean build
  - stage: deploy
    install:
      - ./gradlew clean build -x test
      - docker build -t tomtomhackv4/parkathon-back .
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
    script:
      # export
      - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
      - export GITHUBSTATBOT=tomtomhackv4/parkathon-back
      - export COMMIT=${TRAVIS_COMMIT::7}

      # docker
      - docker build -t $GITHUBSTATBOT:$COMMIT .
      - docker tag $GITHUBSTATBOT:$COMMIT $GITHUBSTATBOT:$TAG
      - docker login -u $DOCKER_USER -p $DOCKER_PASS
      - docker push $GITHUBSTATBOT:$TAG